### ISSUE TITLE
Feature Request: Support for Jetbrains IDEs (Intellij, PyCharm, ...)

### ISSUE THREAD

**Issue by cxor** [ayu-theme/ayu-colors#15]
This colorscheme is simply wonderful. It would be marvelous to have a theme for Jetbrains IDEs such as Intellij and PyCharm. Is it possible?

**Comment by eugeneradionov** [comment]
@cxor someone added ayu dark as a plugin
https://plugins.jetbrains.com/plugin/13888-ayu-dark-color-scheme

**Comment by weiwang11** [comment]
@eugeneradionov That's only for Go programming language, not the whole IDE theme.

**Comment by charlesphil** [comment]
Just writing to update those who may find this ticket online, but someone added Ayu Mirage as a theme through a plugin called [Dark-Themes](https://plugins.jetbrains.com/plugin/18724-dark-themes) earlier this year. I can personally confirm it's available for PyCharm, WebStorm, DataGrip, and AppCode and the page says that it is compatible with all IntelliJ-based IDEs.
![Marketplace Screenshot](https://user-images.githubusercontent.com/71610407/174151730-f41ed810-6601-48dc-be86-7a2de6149686.png)
![Settings](https://user-images.githubusercontent.com/71610407/174151813-d9b3a0a3-31a6-4fdd-9941-10a79d36e5ec.png)

**Comment by cxor** [comment]
Wonderful.
