### ISSUE TITLE
Theme from Webstorm

### ISSUE THREAD

**Issue by lucianovictor** [ayu-theme/ayu-colors#27]
It would be great to have an Ayu theme also created for Jetbrains Webstorm

**Comment by sriharshachilakapati** [comment]
[Ayu Dark.icls.zip](https://github.com/ayu-theme/ayu-colors/files/11275878/Ayu.Dark.icls.zip)

I'm not sure about Webstorm but I've ported the Ayu Dark theme to Android Studio. Since both are based on IntelliJ platform, maybe it'll work for you.

**Comment by lucianovictor** [comment]
but it doesn't have the derivation ayu mirage

**Comment by sriharshachilakapati** [comment]
The ICLS file is just an XML file, so you can edit it and replace the colours yourself to get to the Ayu Mirage. Personally I need more contrast so I go with the dark variant.

**Comment by lucianovictor** [comment]
I will do it, thanks
