### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by imoby** [ayu-theme/ayu-colors#4]
Any chance of getting slack themes for these colors?

**Comment by k15a** [comment]
I think this shouldn't be too hard :) feel free to give it a try.

**Comment by crapthings** [comment]
Any chance of getting iterm2 themes for these official AYU colors?

**Comment by hirakujira** [comment]
@crapthings 
https://github.com/ayu-theme/ayu-vim/tree/master/term

**Comment by JSavage42** [comment]
This is old but give this a shot:

#0A0E14,#3D424D,#3D414D,#e6b450,#504238,#b3b1ad,#62d94c,#e6b450

**Comment by sampi** [comment]
I looked into this again, and made a bit darker version of the Slack sidebar theme, based @with-heart 's solution:

`#1F2430,#1F2430,#181E2B,#6E7A8E,#181E2B,#6E7A8E,#BAE67E,#EC7171,#1F2430,#6E7A8E`

https://slackthemes.net/#/custom#1F2430,1F2430,181E2B,6E7A8E,181E2B,6E7A8E,BAE67E,EC7171,1F2430,6E7A8E

![Screenshot 2020-10-01 at 15 12 28](https://user-images.githubusercontent.com/524272/94813671-9b776d00-03f8-11eb-83b8-dbec56679972.png)
